language: python
cache:
  pip: true
  directories:
    - node_modules
python:
  - 3.6
install:
  - nvm install 8
  - pip install --upgrade coala-bears
  - yarn
script:
  - coala --ci && yarn run eslint && yarn run stylelint && yarn run test:coverage
